### ISSUE TITLE
AttributeError: 'BOARD' object has no attribute 'GetModules'

### ISSUE THREAD

**Issue by Kevin-Pettersson** [0xffox/pcbnew-array-align#1]
Tried running the plugin on Kicad 6.0.9 but I constantly get the error: "AttributeError: 'BOARD' object has no attribute 'GetModules'"

**Comment by 0xffox** [comment]
Thank you for report. Working with [upstream](https://gitlab.com/kicad/code/kicad/-/issues/12898).
